name:                bg
version:             0.1.0.0
synopsis:            Simple project template from stack
description:         Please see README.md
homepage:            https://github.com/5outh/bg#readme
license:             BSD3
author:              Benjamin Kovach
maintainer:          bkovach13@gmail.com
copyright:           2017 Benjamin Kovach
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - diagrams
  - diagrams-lib
  - diagrams-svg
  - colour
  - random
  - split
  - mtl

executables:
  bg-diagrams:
    source-dirs:      src
    main:             Main.hs
